### ISSUE TITLE
Hi! Sorry but , I have tha same error.... with version v1.0.0-alpha2-00365

### ISSUE THREAD

**Issue by romanreal89** [T4MVC/R4MVC#142]
Hi! Sorry but , I have tha same error.... with version v1.0.0-alpha2-00365
What can I do, to fix it? 
Thank you!

> PM> Generate-R4MVC -verbose
>   R4Mvc Generator Tool v1.0.0-alpha2-00365
> Using: Visual Studio Professional 2017 - 15.9.28307.858
> Project: E:\Projects\Git Vero.Tenders\Vero.TendersNetCore.Web\Vero.TendersNetCore.Web.csproj
> Creating Workspace ...
> Loading project ...
> Compiling project ...
> The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: System.Management.Automation.RemoteException

_Originally posted by @romanreal89 in https://github.com/T4MVC/R4MVC/issues/79#issuecomment-542119158_

**Comment by artiomchi** [comment]
I'll make a patch this week so that it outputs any errors in powershell mode. There's most likely a project build or dependency error, which is why it's erroring out

**Comment by artiomchi** [comment]
Hi @romanreal89 

I just pushed a CI build (377) that should finally display proper error messages from the Powershell script. Hopefully this will shed some light on why it's failing to generate the files in your project.

Please note that this is a CI build, so you will have to pull it from the CI repo (see instructions [here](https://github.com/T4MVC/R4MVC/wiki/CI-Builds)) and restart Visual Studio for the new version to be picked up. You'll see the version of the script that runs in the first line of the output, to make sure you're running the new version.

Please let me know if this solved this issue (the lack of proper errors from Powershell) so that I know to merge this to production

**Comment by romanreal89** [comment]
Hi, @artiomchi ! 
Thank you, but I didn't see this build. Last build is 369.

**Comment by IanKemp** [comment]
It's worse with the CI build (even less output, LOL):

```
PM> generate-r4mvc
  R4Mvc Generator Tool v1.0.0-ci-00377

Using: Visual Studio Enterprise 2019 - 16.6.30320.27
Project: <removed>.csproj

Creating Workspace ...
Loading project ...
Compiling project ...
Detected MVC version: 3.1.0.0

Processing controller ControllerName
```

Running the command manually (i.e. via `.\R4Mvc.Tools.exe generate -p "<path\to\removed>.csproj"`) does yield output (see #154).

The reason is the `$ErrorActionPreference = 'Stop'` at the top of `R4MVC.psm1`. `Stop` means PS will **immediately terminate the script on any error**, which means the `catch` block is never entered (see https://stackoverflow.com/a/41518997/70345). I'd suggest just removing that  `$ErrorActionPreference = 'Stop'` setting.

Alternatively, you can add `-ErrorAction 'Continue'` to the `Write-Error` in the `catch` block, but that output is far from useful:

```
Processing controller ControllerName
generate-r4mvc : 
At line:1 char:1
+ generate-r4mvc
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Generate-R4MVC
```

**Comment by IanKemp** [comment]
Running the command manually yields output:

```
PS C:\Users\<removed>\.nuget\packages\r4mvc.tools\1.0.0-ci-00377\tools> .\R4Mvc.Tools.exe generate -p "<path\to\removed>.csproj"
  R4Mvc Generator Tool v1.0.0-ci-00377

Using: Visual Studio Enterprise 2019 - 16.6.30320.27
Project: <path\to\removed>.csproj

Creating Workspace ...
Loading project ...
Compiling project ...
Detected MVC version: 3.1.0.0

Processing controller ControllerName

Unhandled Exception: System.UnauthorizedAccessException: Access to the path '<path\to\ControllerName>.cs' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at R4Mvc.Tools.Services.FilePersistService.WriteFile(SyntaxNode fileTree, String filePath)
   at R4Mvc.Tools.Services.ControllerRewriterService.RewriteControllers(CSharpCompilation compiler)
   at R4Mvc.Tools.Commands.GenerateCommand.Runner.<Run>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at R4Mvc.Tools.Program.<Main>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at R4Mvc.Tools.Program.<Main>(String[] args)
```
